package org.uni.mobilecomputinghomework1

import org.uni.mobilecomputinghomework1.datasource.Food

// AI disclaimer: the following descriptions for each coffee are generated by AI
object FakeFoodData {
    val foodList: List<Food> = listOf(
        Food(
            id = 1,
            imagePath = "https://i.pinimg.com/474x/cb/ee/ab/cbeeabf1e1eee5882e145f3465ada74d.jpg",
            name = "Espresso",
            description = "A strong and concentrated coffee brewed by forcing hot water through finely-ground coffee beans, forming a rich crema on top."
        ),
        Food(
            id = 2,
            imagePath = "https://i.pinimg.com/474x/6f/e8/bd/6fe8bd34e515db63ef5ff0cf807fbb57.jpg",
            name = "Americano",
            description = "A diluted espresso with hot water, giving it a similar strength to regular brewed coffee but with a smoother taste."
        ),
        Food(
            id = 3,
            imagePath = "https://i.pinimg.com/474x/e3/83/f9/e383f9aba12fcabbffd116323690fb57.jpg",
            name = "Latte",
            description = "A creamy coffee drink made with a shot of espresso and steamed milk, topped with a light layer of foam."
        ),
        Food(
            id = 4,
            imagePath = "https://i.pinimg.com/474x/33/44/2e/33442e58a74503c7cef4fc437a4ebc8e.jpg",
            name = "Cappuccino",
            description = "A classic Italian coffee made with equal parts of espresso, steamed milk, and milk foam, creating a rich and frothy texture."
        ),
        Food(
            id = 5,
            imagePath = "https://i.pinimg.com/474x/22/8b/72/228b72a03cb98c19063193cf0188a6a3.jpg",
            name = "Mocha",
            description = "A delicious blend of espresso, steamed milk, and chocolate syrup, often topped with whipped cream."
        ),
        Food(
            id = 6,
            imagePath = "https://i.pinimg.com/474x/d2/0c/e6/d20ce6b882f53f35c58738dab963434b.jpg",
            name = "Macchiato",
            description = "An espresso-based drink with a small amount of foamed milk, creating a bold coffee flavor with a hint of creaminess."
        ),
        Food(
            id = 7,
            imagePath = "https://i.pinimg.com/474x/2d/44/3b/2d443b1934c04acbeb2ba8f5a6f8989a.jpg",
            name = "Flat White",
            description = "A smooth and velvety coffee made with espresso and microfoamed milk, popular in Australia and New Zealand."
        ),
        Food(
            id = 8,
            imagePath = "https://i.pinimg.com/474x/bf/21/bf/bf21bfe4f28ead926a9e473cefea6047.jpg",
            name = "Irish Coffee",
            description = "A warming beverage combining hot coffee, Irish whiskey, sugar, and a layer of thick cream on top."
        ),
        Food(
            id = 9,
            imagePath = "https://i.pinimg.com/474x/62/87/46/628746cee271415648a80d98223fbf97.jpg",
            name = "Cold Brew",
            description = "A smooth and refreshing coffee brewed slowly in cold water for an extended period, creating a naturally sweet and low-acid drink."
        ),
        Food(
            id = 10,
            imagePath = "https://i.pinimg.com/474x/ba/59/01/ba590142187dcaf2dd74f22f8c27c765.jpg",
            name = "Affogato",
            description = "A simple yet indulgent dessert made by pouring a shot of hot espresso over a scoop of vanilla ice cream."
        ),
        // Newly added items
        Food(
            id = 11,
            imagePath = "https://i.pinimg.com/474x/c0/37/aa/c037aa07061a489ec1cbdb37acba6b45.jpg",
            name = "Turkish Coffee",
            description = "A traditional method of brewing unfiltered coffee, finely ground and simmered in a pot, often served with foam on top."
        ),
        Food(
            id = 12,
            imagePath = "https://i.pinimg.com/474x/ca/36/b8/ca36b8f2eaeec31498d7dafbeddea126.jpg",
            name = "Cortado",
            description = "A balanced coffee drink made with equal parts espresso and steamed milk, reducing the acidity of the espresso."
        ),
        Food(
            id = 13,
            imagePath = "https://i.pinimg.com/474x/86/50/a2/8650a2e29ec10a92a53af08f6928ec4a.jpg",
            name = "Iced Coffee",
            description = "Chilled coffee served over ice, often sweetened and mixed with milk or cream for a refreshing drink."
        ),
        Food(
            id = 14,
            imagePath = "https://i.pinimg.com/474x/33/ba/cf/33bacf26dc45f0c54e784745cec5286a.jpg",
            name = "Vietnamese Coffee",
            description = "A strong and sweet coffee made with dark roast coffee and condensed milk, often served hot or iced."
        )
    )
}