//package org.uni.mobilecomputinghomework1
//
//import org.uni.mobilecomputinghomework1.datasource.Food
//
//// AI disclaimer: the following descriptions for each food are generated by AI
//object FakeFoodData {
//    val foodList: List<Food> = listOf(
//        Food(
//            id = 1,
//            imagePath = "https://i.pinimg.com/736x/59/ad/7d/59ad7dfa8c1a33019081315e262f20b5.jpg",
//            name = "Cake",
//            description = "A sweet and fluffy baked dessert, often layered and frosted, perfect for celebrations and special occasions."
//        ),
//        Food(
//            id = 2,
//            imagePath = "https://i.pinimg.com/736x/39/94/ae/3994ae82018f624dc7fbc42f8abf3426.jpg",
//            name = "Cookie",
//            description = "A small, flat, and crispy or chewy treat, typically baked with sugar, butter, and flour, often with chocolate chips or nuts."
//        ),
//        Food(
//            id = 3,
//            imagePath = "https://i.pinimg.com/736x/ef/81/2e/ef812ec3773d7f1038d88c79f10d2f7b.jpg",
//            name = "Fish",
//            description = "A versatile and nutritious food, cooked in a variety of ways such as grilled, baked, or fried, often served with herbs and lemon."
//        ),
//        Food(
//            id = 4,
//            imagePath = "https://i.pinimg.com/736x/98/6e/80/986e8020d901fe1c313e9460495ec5c3.jpg",
//            name = "Pancake",
//            description = "A soft and fluffy breakfast delight made from a batter and cooked on a griddle, usually topped with syrup, butter, or fruits."
//        ),
//        Food(
//            id = 5,
//            imagePath = "https://i.pinimg.com/736x/c5/2d/45/c52d454bf256841ea8934cd3d760d7b1.jpg",
//            name = "Pasta",
//            description = "An Italian classic made from wheat and water, available in various shapes, served with sauces like marinara, Alfredo, or pesto."
//        ),
//        Food(
//            id = 6,
//            imagePath = "https://i.pinimg.com/736x/34/f4/8f/34f48f5c56c938642b80b0555e5adf82.jpg",
//            name = "Pizza",
//            description = "A beloved Italian dish made with a baked dough base, topped with tomato sauce, cheese, and a variety of toppings like vegetables or meat."
//        ),
//        Food(
//            id = 7,
//            imagePath = "https://i.pinimg.com/736x/92/fb/c4/92fbc497e189aced07708b989c9b8ce0.jpg",
//            name = "Salad",
//            description = "A healthy mix of fresh vegetables, greens, and sometimes fruits, nuts, or proteins, dressed with vinaigrette or creamy sauces."
//        ),
//        Food(
//            id = 8,
//            imagePath = "https://i.pinimg.com/736x/bb/28/7d/bb287d3944ef3c0b9edbc9286006f6d6.jpg",
//            name = "Sandwich",
//            description = "A convenient and tasty meal made with bread slices filled with a variety of ingredients like meats, cheeses, and vegetables."
//        ),
//        Food(
//            id = 9,
//            imagePath = "https://i.pinimg.com/736x/fc/3d/d8/fc3dd8e101ee74115f0377a58e88ff6b.jpg",
//            name = "Soup",
//            description = "A warm and comforting dish made by simmering vegetables, meat, or legumes in broth, perfect for a cozy meal."
//        ),
//        Food(
//            id = 10,
//            imagePath = "https://i.pinimg.com/736x/6d/ba/91/6dba91c1fdb5d4939c7e9d65420cbd4c.jpg",
//            name = "Steak",
//            description = "A thick cut of beef, typically grilled or pan-seared to your preferred level of doneness, often served with sides like mashed potatoes or vegetables."
//        ),
//        Food(
//            id = 11,
//            imagePath = "https://i.pinimg.com/736x/90/e4/82/90e4824224b82a769281ae3502e92e6c.jpg",
//            name = "Burger",
//            description = "A ground beef patty, usually served in a soft bun with various toppings such as lettuce, tomato, cheese, pickles, and sauces."
//        ),
//        Food(
//            id = 12,
//            imagePath = "https://i.pinimg.com/736x/e6/b6/38/e6b638870b04b383e366d18ffafca9f0.jpg",
//            name = "Rice",
//            description = "A staple food made from boiled or steamed grains, commonly served as a side dish or as a base for various dishes like curries, stir-fries, or sushi."
//        ),
//        Food(
//            id = 13,
//            imagePath = "https://i.pinimg.com/736x/68/e0/7f/68e07f7a9af01b7c96f488f828b5681c.jpg",
//            name = "Meatball",
//            description = "Small, round pieces of ground meat, often mixed with breadcrumbs and spices, then baked, fried, or simmered in a sauce."
//        ),
//        Food(
//            id = 14,
//            imagePath = "https://i.pinimg.com/736x/f1/0b/cb/f10bcbd08eedf64d9d0f341673ad3992.jpg",
//            name = "Stew",
//            description = "A hearty and comforting dish made by slowly simmering meat, vegetables, and spices in a flavorful broth, often served with bread or rice."
//        ),
//    )
//}


package org.uni.mobilecomputinghomework1

import org.uni.mobilecomputinghomework1.datasource.Food

// AI disclaimer: the following descriptions for each coffee are generated by AI
object FakeFoodData {
    val foodList: List<Food> = listOf(
        Food(
            id = 1,
            imagePath = "https://i.pinimg.com/474x/cb/ee/ab/cbeeabf1e1eee5882e145f3465ada74d.jpg",
            name = "Espresso",
            description = "A strong and concentrated coffee brewed by forcing hot water through finely-ground coffee beans, forming a rich crema on top."
        ),
        Food(
            id = 2,
            imagePath = "https://i.pinimg.com/474x/6f/e8/bd/6fe8bd34e515db63ef5ff0cf807fbb57.jpg",
            name = "Americano",
            description = "A diluted espresso with hot water, giving it a similar strength to regular brewed coffee but with a smoother taste."
        ),
        Food(
            id = 3,
            imagePath = "https://i.pinimg.com/474x/e3/83/f9/e383f9aba12fcabbffd116323690fb57.jpg",
            name = "Latte",
            description = "A creamy coffee drink made with a shot of espresso and steamed milk, topped with a light layer of foam."
        ),
        Food(
            id = 4,
            imagePath = "https://i.pinimg.com/474x/33/44/2e/33442e58a74503c7cef4fc437a4ebc8e.jpg",
            name = "Cappuccino",
            description = "A classic Italian coffee made with equal parts of espresso, steamed milk, and milk foam, creating a rich and frothy texture."
        ),
        Food(
            id = 5,
            imagePath = "https://i.pinimg.com/474x/22/8b/72/228b72a03cb98c19063193cf0188a6a3.jpg",
            name = "Mocha",
            description = "A delicious blend of espresso, steamed milk, and chocolate syrup, often topped with whipped cream."
        ),
        Food(
            id = 6,
            imagePath = "https://i.pinimg.com/474x/d2/0c/e6/d20ce6b882f53f35c58738dab963434b.jpg",
            name = "Macchiato",
            description = "An espresso-based drink with a small amount of foamed milk, creating a bold coffee flavor with a hint of creaminess."
        ),
        Food(
            id = 7,
            imagePath = "https://i.pinimg.com/474x/2d/44/3b/2d443b1934c04acbeb2ba8f5a6f8989a.jpg",
            name = "Flat White",
            description = "A smooth and velvety coffee made with espresso and microfoamed milk, popular in Australia and New Zealand."
        ),
        Food(
            id = 8,
            imagePath = "https://i.pinimg.com/474x/bf/21/bf/bf21bfe4f28ead926a9e473cefea6047.jpg",
            name = "Irish Coffee",
            description = "A warming beverage combining hot coffee, Irish whiskey, sugar, and a layer of thick cream on top."
        ),
        Food(
            id = 9,
            imagePath = "https://i.pinimg.com/474x/62/87/46/628746cee271415648a80d98223fbf97.jpg",
            name = "Cold Brew",
            description = "A smooth and refreshing coffee brewed slowly in cold water for an extended period, creating a naturally sweet and low-acid drink."
        ),
        Food(
            id = 10,
            imagePath = "https://i.pinimg.com/474x/ba/59/01/ba590142187dcaf2dd74f22f8c27c765.jpg",
            name = "Affogato",
            description = "A simple yet indulgent dessert made by pouring a shot of hot espresso over a scoop of vanilla ice cream."
        ),
        // Newly added items
        Food(
            id = 11,
            imagePath = "https://i.pinimg.com/474x/c0/37/aa/c037aa07061a489ec1cbdb37acba6b45.jpg",
            name = "Turkish Coffee",
            description = "A traditional method of brewing unfiltered coffee, finely ground and simmered in a pot, often served with foam on top."
        ),
        Food(
            id = 12,
            imagePath = "https://i.pinimg.com/474x/ca/36/b8/ca36b8f2eaeec31498d7dafbeddea126.jpg",
            name = "Cortado",
            description = "A balanced coffee drink made with equal parts espresso and steamed milk, reducing the acidity of the espresso."
        ),
        Food(
            id = 13,
            imagePath = "https://i.pinimg.com/474x/86/50/a2/8650a2e29ec10a92a53af08f6928ec4a.jpg",
            name = "Iced Coffee",
            description = "Chilled coffee served over ice, often sweetened and mixed with milk or cream for a refreshing drink."
        ),
        Food(
            id = 14,
            imagePath = "https://i.pinimg.com/474x/33/ba/cf/33bacf26dc45f0c54e784745cec5286a.jpg",
            name = "Vietnamese Coffee",
            description = "A strong and sweet coffee made with dark roast coffee and condensed milk, often served hot or iced."
        )
    )
}