package org.uni.mobilecomputinghomework1

import org.uni.mobilecomputinghomework1.datasource.Food

// AI disclaimer: the following descriptions for each coffee are generated by AI
object FakeFoodData {
    val foodList: List<Food> = listOf(

        Food(
            id = 1,
            imagePath = "https://i.pinimg.com/474x/33/ba/cf/33bacf26dc45f0c54e784745cec5286a.jpg",
            name = "Vietnamese Coffee",
            description = "A strong and sweet coffee made with dark roast coffee and condensed milk, often served hot or iced."
        ),
        Food(
            id = 2,
            imagePath = "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/17/bf/17/37/img-20190505-125738543.jpg?w=1100&h=600&s=1",
            name = "Pizza Margherita",
            description = "A classic Italian pizza topped with fresh tomatoes, mozzarella, basil, and a drizzle of olive oil."
        )

    )

}